// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztkymiebzejjplimrwyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0a3ltaWViemVqanBsaW1yd3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTQ0MjksImV4cCI6MjA2MjUzMDQyOX0.irNLWvuAKi3C_FKe5F7XFc5Ku-sucWiWXWZ_mxnARSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);